### ISSUE TITLE
Memory Leak Bug 

### ISSUE THREAD

**Issue by marian-craciunescu** [marian-craciunescu/ESP32Ping#4]
I've added a new mem_free in the latest source.
Can somebody give it a try and test it?

**Comment by adynis** [comment]
Thanks !! :)
I will try in a couple of hours and come back with feedback.

Adi,

**Comment by adynis** [comment]
I confirm, adding "mem_free()" solves the issue !! The free memory was stable immediately and stayed like this for 1hour of continues pings ... so that was it !! Thanks.

Ps. there are also other issues to address, but I wait for a recommendation from you for the best method to address them.

**Comment by marian-craciunescu** [comment]
Great.
Let's add the issues and start solving them
